version: "2"
services:
  mongo:
    image: mongo:latest
    volumes:
      - './mongo/data/:/data/db'
    ports:
      - 27017:27017

  api:
    image: "matheuspiment/todo-api"
    restart: "always"
    environment:
      NODE_ENV: "development"
    links:
      - "mongo"
    expose:
      - 3000
