// flow-typed signature: c66ab49bcec871ca2f7a4a317a3608a5
// flow-typed version: <<STUB>>/koa-graphql-batch_v^1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-graphql-batch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-graphql-batch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-graphql-batch/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-graphql-batch/lib/index.js' {
  declare module.exports: $Exports<'koa-graphql-batch/lib/index'>;
}
