// flow-typed signature: 9973975953365aa7e55feb54979e8044
// flow-typed version: <<STUB>>/repl-promised_v^0.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repl-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repl-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'repl-promised/index' {
  declare module.exports: $Exports<'repl-promised'>;
}
declare module 'repl-promised/index.js' {
  declare module.exports: $Exports<'repl-promised'>;
}
